### ISSUE TITLE
SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by jcw** [dominictarr/tacodb#7]
Hello - I'm trying out the "ws" example (Mac OSX 10.8.4, Safari 6.0.5, node 0.10.15).

I cloned the git directory and made it available to npm as follows:

```
cd tacodb
npm install
(had to also add "npm install multilevel" extra, I think)
npm link
cd examples/ws
tacodb local ./server.js --name server
```

So far so good, then I went to localhost:8000 - but the console log gives me this error:

```
SyntaxError: JSON.parse (on line "localhost:541")
```

The http & changes examples worked as described, so I'm kind of puzzled as to what I could be doing wrong... any tips would be much appreciated.

-jcw

**Comment by dominictarr** [comment]
Hmm, this is a strange error...

It seems to be trying to parse the index.html ...

not sure why this is...
